explicit dashboard; adminer (one at a time); staging

diff --git a/startTraefik b/startTraefik
--- a/startTraefik
+++ b/startTraefik
@@ -19,6 +19,7 @@ set -e
 # 1/3/2020    Added -d for dev mode; Removed license.
 # 1/7/2020    Added -f for freshen mode.
 # 1/8/2020    LegacyChecks for old version cleanups
+# 1/17/2020   API/Adminer/Staging flags
 #
 ##################################################################
 # Help ###########################################################
@@ -29,12 +30,14 @@ Help()
 	# Display Help
 	echo "Generates a docker-compose.yml configuration for the RHDWP stack."
 	echo
-	echo "Syntax: startTraefik [-h][-d][-a][-f]"
+	echo "Syntax: startTraefik [-h][-d][-f][-a][-m project_name][-s]"
 	echo "options:"
-	echo "-h    Print this Help."
-	echo "-d    Development mode (also enables authenticated Traefik dashboard)"
-	echo "-a    Enable dashboard."
-	echo "-f    Freshen site stacks in www/ directory"
+	echo "-h         Print this Help."
+	echo "-d         Development mode (implies -a)"
+	echo "-f         Freshen site stacks in www/ directory"
+	echo "-a         Enable dashboard."
+	echo "-m name    Enable MySQL adminer dashboard for a project"
+	echo "-s         LetsEncrypt Staging server"
 	echo
 }
 
@@ -129,9 +132,21 @@ GenerateComposeFile()
 	# Create/edit docker-compose.yml
 	cp "$composeTemplate" "$composeTemporary"
 
-	if [[ "${api}" = true ]]; then
+	if [[ "$api" = true ]]; then
 		# Uncomment all commented lines to enable
-		sed 's/#\s//g' "$composeTemplate" > "$composeTemporary"
+		# sed -i 's/#\s//g' "$composeTemporary"
+		sed -i '/## RHDWP: API ##/,/## RHDWP: API end ##/s/[^#]# / /g' "$composeTemporary"
+	fi
+
+	if [[ "$adminer" = true ]] && [[ ! -z "$adminerProject" ]]; then
+		# Enable adminer for specified project (using PROJECT_NAME envvar)
+		# sed -i "s/%%project_label%%/${adminerProject}/g" "$composeTemporary"
+		sed -i '/## RHDWP: Adminer ##/,/## RHDWP: Adminer end ##/s/[^#]# / /g' "$composeTemporary"
+		sed -i "/## RHDWP: Adminer ##/,/## RHDWP: Adminer end ##/s/%%project_label%%/${adminerProject}/g" "$composeTemporary"
+	fi
+
+	if [[ "$certStaging" = true ]]; then
+		sed -i '/## RHDWP: LetsEncrypt Staging ##/,/## RHDWP: LetsEncrypt Staging end ##/s/[^#]# / /g' "$composeTemporary"
 	fi
 
 	mv "$composeTemporary" "$composeFile"
@@ -210,10 +225,12 @@ composeFile="${traefikDir}/docker-compose.yml"
 devMode=false
 freshenMode=false
 api=
+adminer=
+certStaging=
 network=web
 
 ## Get options
-while getopts "hdaf" opt; do
+while getopts "hdfam:s" opt; do
 	case "$opt" in
 	h) # display Help
 		Help
@@ -227,9 +244,23 @@ while getopts "hdaf" opt; do
 	a) # API/Dashboard enabled
 		api=true
 		;;
+	m) # Enable adminer for a project
+		if [[ ! -z "$OPTARG" ]]; then
+			adminer=true
+			adminerProject=${OPTARG}
+			echo "Adminer enabled for ${adminerProject}"
+		else
+			echo "Error: The -m option requires an argument."
+			exit 1
+		fi
+		;;
 	f) # Freshen sites (www/ site stacks)
 		echo "Freshen sites"
 		freshenMode=true
+		;;
+	s) # LetsEncrypt staging mode
+		echo "Using LetsEncrypt staging server"
+		certStaging=true
 		;;
 	\?) # invalid option
 		echo "Invalid option: -$OPTARG" >&2
