old version housekeeping

diff --git a/startTraefik b/startTraefik
--- a/startTraefik
+++ b/startTraefik
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -ex
+set -e
 
 ##################################################################
 # startTraefik ###################################################
@@ -18,6 +18,7 @@ set -ex
 # 1/1/2020    Sanity checks.
 # 1/3/2020    Added -d for dev mode; Removed license.
 # 1/7/2020    Added -f for freshen mode.
+# 1/8/2020    LegacyChecks for old version cleanups
 #
 ##################################################################
 # Help ###########################################################
@@ -58,40 +59,50 @@ SanityChecks()
 	done
 }
 
+LegacyChecks()
+{
+	# Housekeeping
+	## Remove extraneous directories
+	if [[ -d "${rootDir}/log" ]]; then
+		rm -rf "${rootDir}/log"
+	fi
+}
+
+
 AskEnv()
 {
 	# Verify .env values
 
 	# CloudFlare account email
 	while [[ -z "$CF_API_EMAIL" ]]; do
-	read -r -p "CloudFlare account email: " CF_API_EMAIL
+		read -r -p "CloudFlare account email: " CF_API_EMAIL
 	done
 
 	# CloudFlare API Key
 	while [[ -z "$CF_API_KEY" ]]; do
-	read -r -p "CloudFlare API Key: " CF_API_KEY
+		read -r -p "CloudFlare API Key: " CF_API_KEY
 	done
 
 	# Mailgun API Key
 	while [[ -z "$MG_API_KEY" ]]; do
-	read -r -p "MailGun API Key: " MG_API_KEY
+		read -r -p "MailGun API Key: " MG_API_KEY
 	done
 
 	if [[ "$devMode" = true ]]; then
-	# SMTP login for dev mode
-	while [[ -z "$DEV_SMTP_LOGIN" ]]; do
-		read -r -p "RHDEV SMTP Login (Mailgun): " DEV_SMTP_LOGIN
-	done
+		# SMTP login for dev mode
+		while [[ -z "$DEV_SMTP_LOGIN" ]]; do
+			read -r -p "RHDEV SMTP Login (Mailgun): " DEV_SMTP_LOGIN
+		done
 
-	# Mailgun API Key
-	while [[ -z "$DEV_SMTP_PASS" ]]; do
-		read -r -p "RHDEV SMTP Pass (Mailgun): " DEV_SMTP_PASS
-	done
+		# Mailgun API Key
+		while [[ -z "$DEV_SMTP_PASS" ]]; do
+			read -r -p "RHDEV SMTP Pass (Mailgun): " DEV_SMTP_PASS
+		done
 
-	# SMTP login for dev mode
-	while [[ -z "$DEV_SMTP_FROM" ]]; do
-		read -r -p "RHDEV SMTP From: " DEV_SMTP_FROM
-	done
+		# SMTP login for dev mode
+		while [[ -z "$DEV_SMTP_FROM" ]]; do
+			read -r -p "RHDEV SMTP From: " DEV_SMTP_FROM
+		done
 	fi
 }
 
@@ -119,8 +130,8 @@ GenerateComposeFile()
 	cp "$composeTemplate" "$composeTemporary"
 
 	if [[ "${api}" = true ]]; then
-	# Uncomment all commented lines to enable
-	sed 's/#\s//g' "$composeTemplate" > "$composeTemporary"
+		# Uncomment all commented lines to enable
+		sed 's/#\s//g' "$composeTemplate" > "$composeTemporary"
 	fi
 
 	mv "$composeTemporary" "$composeFile"
@@ -168,6 +179,7 @@ SetupFiles()
 
 FreshenSites()
 {
+	local _cwd="$PWD"
 	for d in "${wwwDir}"/*; do
 		dir="${d##*/}"
 
@@ -181,7 +193,7 @@ FreshenSites()
 			sudo -u "$USER" ./buildStack -q
 		fi
 		
-		cd "$cwd"
+		cd "$_cwd"
 	done
 }
 
@@ -192,7 +204,6 @@ FreshenSites()
 rootDir="$(dirname "$(realpath "$0")")"
 traefikDir="${rootDir}/traefik"
 wwwDir="${rootDir}/www"
-utilsDir="${rootDir}/utils"
 composeTemplate="${traefikDir}/docker-compose-template.yml"
 composeTemporary="${traefikDir}/docker-compose.yml~"
 composeFile="${traefikDir}/docker-compose.yml"
@@ -229,6 +240,7 @@ done
 
 ## Before we begin...
 SanityChecks
+LegacyChecks
 
 ## Generate LetsEncrypt storage and log files
 SetupFiles
