Formatting (tabs) and cleaned var usage

diff --git a/startTraefik b/startTraefik
--- a/startTraefik
+++ b/startTraefik
@@ -11,12 +11,11 @@ set -e
 # Change History #################################################
 ##################################################################
 #
-# 12/24/19    Finally added this changelog.
-#               Add documentation and restructure for long-term
-#               happiness, and a Help function.
-#               Yummy refactoring.
-# 1/1/20      Sanity checks.
-# 1/3/20      Added -d for dev mode; Removed license.
+# 12/24/2019	Finally added this changelog.
+#								Add documentation and restructure for long-term
+#								happiness, and a Help function.
+# 1/1/2020		Sanity checks.
+# 1/3/2020		Added -d for dev mode; Removed license.
 #
 ##################################################################
 # Help ###########################################################
@@ -50,10 +49,10 @@ SanityChecks()
 	
 	deps=( docker docker-compose )
 	for i in "${deps[@]}"; do
-		if ! hash "$i" 2>/dev/null; then
-			printf "Error: %s was not found in PATH. Please check that it's installed before proceeding.\n" "$i"
-			exit 1
-		fi
+	if ! hash "$i" 2>/dev/null; then
+		printf "Error: %s was not found in PATH. Please check that it's installed before proceeding.\n" "$i"
+		exit 1
+	fi
 	done
 }
 
@@ -130,46 +129,47 @@ SetupFiles()
 	# Generate storage and log files, if necessary
 
 	## Logs
-	logdir=./log
+	logdir="${traefikDir}/log"
 	if [[ ! -d "$logdir" ]]; then
-	        mkdir "$logdir"
+		mkdir "$logdir"
 	fi
 
 	log="${logdir}/error.log"
 	if [[ ! -f "$log" ]]; then
-	        touch "$log"
+		touch "$log"
 	fi
 
 	## LetsEncrypt storage
-	acme=./traefik/acme.json
+	acme="${traefikDir}/acme.json"
 	if [[ ! -f "$acme" ]]; then
-	        sudo touch "$acme"
-	        sudo chown www-data:www-data "$acme"
-	        sudo chmod 600 "$acme"
+		sudo touch "$acme"
+		sudo chown www-data:www-data "$acme"
+		sudo chmod 600 "$acme"
 	fi
 
 	## Environment variables file
-        env_file=./traefik/.env
-        if [[ -r "$env_file" ]]; then
-                # shellcheck disable=SC1091
-                # shellcheck source=/srv/rhdwp/traefik/.env
-                . "$env_file"
-        fi
+	env_file="${traefikDir}/.env"
+	if [[ -r "$env_file" ]]; then
+		# shellcheck disable=SC1091
+		# shellcheck source=/srv/rhdwp/traefik/.env
+		. "$env_file"
+	fi
 
 	## Create sites directory
-        if [[ ! -d ./www ]]; then
-                mkdir www
-        fi
+	if [[ ! -d "${rootDir}/www" ]]; then
+		mkdir www
+	fi
 
 	## wp-cli permissions
-	sudo chown -R www-data:www-data ./wp-cli
+	sudo chown -R www-data:www-data "${rootDir}/wp-cli"
 }
 
 ##################################################################
 # Main ###########################################################
 ##################################################################
 ## Initialize variables
-traefikDir=$(dirname "$(realpath "$0")")"/traefik"
+rootDir=$(dirname "$(realpath "$0")")
+traefikDir="${rootDir}/traefik"
 composeTemplate="${traefikDir}/docker-compose-template.yml"
 composeTemporary="${traefikDir}/docker-compose.yml~"
 composeFile="${traefikDir}/docker-compose.yml"
@@ -181,26 +181,26 @@ network=web
 ## Get options
 while getopts "hdaf" opt; do
 	case "$opt" in
-		h)  # display Help
-			Help
-			exit
-			;;
-		d)  # Development mode
-			echo "Development mode enabled."
-			devMode=true
-			api=true
-			;;
-		a)  # API/Dashboard enabled
-			api=true
-			;;
-		f)  # force rebuild
-			echo "Using --force-recreate..."
-			flags='--force-recreate'
-			;;
-		\?) # invalid option
-			echo "Invalid option: -$OPTARG" >&2
-			exit 1
-			;;
+	h) # display Help
+		Help
+		exit
+		;;
+	d) # Development mode
+		echo "Development mode enabled."
+		devMode=true
+		api=true
+		;;
+	a) # API/Dashboard enabled
+		api=true
+		;;
+	f) # force rebuild
+		echo "Using --force-recreate..."
+		flags='--force-recreate'
+		;;
+	\?) # invalid option
+		echo "Invalid option: -$OPTARG" >&2
+		exit 1
+		;;
 	esac
 done
 
@@ -223,4 +223,4 @@ WriteEnv
 GenerateComposeFile
 
 ## Start traefik
-( cd ./traefik && ( docker-compose down || true ) && docker-compose up -d --remove-orphans ${flags:-} )
+( cd "${traefikDir}" && ( docker-compose down || true ) && docker-compose up -d --remove-orphans ${flags:-} )
